### ISSUE TITLE
Configurable option to make plugin return an error

### ISSUE THREAD

**Issue by dustinspecker** [dustinspecker/gulp-alex#2]

**Comment by wooorm** [comment]
There’s some interesting stuff related to this in [vfile-reporter](https://github.com/wooorm/vfile-reporter), (which power alex, mdast, and soon others, so not everything is applicable solely to alex), such as supporting `quiet` and `silent`, and detecting when a file has “failed”.

**Comment by dustinspecker** [comment]
That looks perfect. Thanks!

**Comment by dustinspecker** [comment]
vfile-reporter did the trick. Thanks!

**Comment by wooorm** [comment]
Cool :)
