### ISSUE TITLE
Way to ignore certain rules, or mark instances okay?

### ISSUE THREAD

**Issue by agnoster** [dustinspecker/gulp-alex#6]
I'd like to make gulp-alex part out our CI, but to do that I need to make sure that all the output is actionable. There are two types of situations where that doesn't seem currently workable:

1. Certain rules don't make sense in our text, e.g. "`pop` may be insensitive, use `parent` instead" - well and good when talking about parents, but when you're talking about stacks/queues, less so.
2. Certain rules don't make sense in context, e.g. "`him` may be insensitive, use `their`, `theirs`, `them` instead" - again, absolutely agree except that if the subject of the sentence identifies as male it could actually be disrespectful to not use the correct pronoun.

Any way to customize this?

**Comment by dustinspecker** [comment]
Unfortunately, that's a limitation of Alex. To my knowledge it doesn't support ignoring rules or portions of the files.

I can spend some time this weekend looking into it, but it would probably be more appropriate at the Alex level instead of the plugin level.

**Comment by agnoster** [comment]
Gotcha. There would still need to be some way to pass the options through, but potentially that could happen via something like a .alex.rc file or something...
